# Reemplaza TU_ORG y la projectKey por los valores que te dé SonarCloud
# al crear el proyecto (Account > Organizations).
sonar.organization=samuscq
sonar.projectKey=SamusCQ_url-shortener-cicd
sonar.projectName=URL Shortener

sonar.sources=src
sonar.tests=tests
sonar.test.inclusions=tests/**/*.test.js
sonar.exclusions=node_modules/**,coverage/**

# Cobertura generada por Jest (formato lcov)
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# El JS del frontend corre en el navegador (no en los tests): se excluye de cobertura.
sonar.coverage.exclusions=src/public/**

# Hace que el scan espere el resultado del Quality Gate y falle el pipeline si no pasa
sonar.qualitygate.wait=true
